INSERT INTO `diagnostics` (`id`,`description`) VALUES (9,'aucun');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (10,'Fracture ancienne du poignet droit');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (11,'fracture non consolideé de la pointe antéro-inférieure du scaphoide droit');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (12,'OTITE DROITE+ INFECTION URINAIRE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (13,'otite dte+infection urinaire');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (14,'INFECTION URINAIRE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (15,'CRURALGIES DROITES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (16,'GROSSESSE EVOLUTIVE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (17,'LOMBALGIIES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (18,'sd douloureux des extremités');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (19,'HTA 18/12');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (20,'gonalgies');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (21,'Sd grippal');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (22,'anxiete');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (23,'polyarthralgies ');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (24,'COLOPATHIE FONCTIONNELLE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (25,'gonalgies chroniques');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (26,'SD FEBRILE ANGINES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (27,'INF URINAIRE SUR ADENOME DE PROSTATE +ALLERGIE RESP');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (28,'SCIATIQUE DTE+BRONCHITE +AEROCOLIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (29,'OTITE DROITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (30,'BRONCHITE ASTHMATIFORME');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (31,'diagnostique');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (32,'ANGINES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (33,'GASTROENTERITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (34,'grossesse évolutive de 8semaines environ');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (35,'GASTRALGIES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (36,'HTA');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (37,'INFEC URINAIRE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (38,'DOULEURS FID');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (39,'TRAUMATISME LOMBOSACRE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (40,'GROSSESSE DE 8SEM ENVIRONS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (41,'myalgies');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (42,'pyrosis');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (43,'oxyurose');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (44,'adenome prostatique');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (45,'VARICES MI');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (46,'EX CLINIQUE NORMAL');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (47,'HYMEN NE PRESENTANT PAS DE SIGNES DE DEFLORATION RECENTE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (48,'infection genitale');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (50,'COLIQUES ABDOMINALES +ENURESIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (51,'CORPS ETRANGER PLANTE PIED DROIT');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (52,'ARTRALGIES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (53,'IRRITATION');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (54,'SCIATALGIES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (55,'allergie respiratoire+angines');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (56,'AMENORRHEE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (57,'OBESITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (58,'BRONCHITE AIGUE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (59,'DOULEURS CERVICALES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (60,'GROSSESSE EVOLUTIVE DE 18 SEM ENVIRONS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (61,'INFECTION OMBILIC');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (62,'VERTIGES HYPERCHOLESTEROLEMIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (63,'PITYRIASIS VERSICOLOR');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (64,'PARALYSIE DES MEMBRES ');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (65,'PERIARTHRITE SCAPULOHUMERALE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (66,'GROSSESSE EVOLUTIVE DE 7 SEM');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (67,'MIGRAINE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (69,'DIABETE 2');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (70,'grossesse evolutive de 6semaies environs');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (71,'COLIQUES NEPHRETIQUES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (72,'APTITUDE PHYSIQUE PRENUPTIALE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (73,'PLAIE INFECTEE DU MEDIUS GAUCHE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (74,'COLIQUES ABDOMINALES NAUSEES  ');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (75,'TAKYCARDIE+ NERVOSITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (76,'CERVICALGIES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (78,'OXYURES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (79,'GROSSESSE EVOLUTIVE DE 5MOIS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (80,'CONJONCTIVITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (81,'AVP');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (82,'VISITE A DOMICILE  PATIENT AGE CACHEXIQUE DESHYDRATE ANOREXIQUE INCONTINENT URINAIRE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (83,'CACHEXIE DESHYDRATATION ASTHENIE ANOREXIE INCONTINENCE URINAIRE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (84,'TUMEUR DU POUMON GAUCHE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (85,'HTA DID  KC PANCREAS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (86,'MIGRAINE  RHINOPHARYNGITE  INF URINAIRE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (87,'INFECTION GENITALE  +COLOPATHIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (88,'DNID SUIVI');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (89,'HTA+ AEROCOLIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (90,'conjonctivite allergique');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (91,'LOMBOSCIATIQUE +SECHERESSE DE LA BOUCHE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (92,'ENURESIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (93,'COLIQUES HEPATIQUES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (94,'HEMORROIDES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (95,'MYCOSE DES FESSES  +  CERTIFICAT MED PRENUPTIAL');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (96,'LOMBOSCIATALGIES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (97,'AMENORRHEE+PERTES GENITALES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (98,'TRAUMA OEIL G');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (99,'VIOLENCE CONJUGALE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (101,'DOULEURS DU BASSIN ET DES MI');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (102,'TENSION NERVEUSE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (103,'MUCOSE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (104,'DLRS SCAPULO-HUMERALES DTES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (105,'ERUPTION CUTANEE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (107,'APTITUDE PHYSIQUE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (108,'DORSALGIES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (109,'grossesse évolutive de 32semaines');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (110,'POINT DE COTE HYPOCHONDRE G');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (112,'ICTERE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (113,'INTOXICATION ALIMENTAIRE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (114,'DYSPNEE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (115,'NERVOSITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (117,'INF GENITALE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (118,'ONYCHOMYCOSE DES PIEDS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (119,'TRACHEOBRONCHITE FEBRILE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (120,'IMPUISSANCE SEXUELLE +DNID');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (121,'DOULEURS PERIOMBILICALES+ NAUSEES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (122,'cicatrice douloureuse sourcil gauche');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (123,'DLRS ABDOMINALES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (124,'DOULEURS ABDOMINALES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (125,'hypersudation=myalgies');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (126,'DYSPAREUNIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (127,'CERTIFICAT MEDICAL PRENUPTIAL');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (129,'DLS THORACIQUES DTES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (130,'DLRS PIED GAUCHE+BRONCHITE TABAGIQUE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (131,'MALADIE DE CROHN PROBABLE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (132,'ANEMIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (133,'CEPHALEE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (134,'OREILLONS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (135,'SURMENAGE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (136,'DID + HTA + INSUFF RENALE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (137,'COLIQUES ABD+ DIARRHEE+ANEMIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (138,'COLIQUES ABD+DIARRHEE +ANEMIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (139,'TRAUMA GENOU DROIT AVP');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (140,'COLOPATHIE  FONCTIONNELLE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (141,'PNEUMOPATHIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (142,'ASTHENIE SEXUELLE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (143,'MYCOSE DES PLIS ');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (144,'COLOPATHIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (145,'RHINITE ALLERGIQUE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (146,'RHUME');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (147,'ALLERGIE CUTANEE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (148,'ARTHRITE CHEVILLE DTE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (149,'ALLERGIE ET MYCOSE CUTANEE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (150,'suspicion de grossesse');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (151,'PHARYNGITE+MYCOSE DES JAMBES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (152,'dlrs des pieds');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (153,'TABAGISME CHRONIQUE ARRETE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (154,'POINT DE COTE THORACIQUE G');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (155,'OBESITE+ASTHENIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (157,'VERTIGES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (158,'AVP TRAUMA LEGER ');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (159,'STRESS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (160,'AGRESSION  Ecchymoses multiples de la tete');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (162,'CRISE ASTHME+ANGINES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (163,'VARICELLE+ANGINES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (164,'SIGNES DE PRE MENOPAUSE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (165,'CARIES DENTAIRES SURINFECTEES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (166,'RETARD STATUROPONDERAL');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (167,'COURBATURES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (168,'ASTHENIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (169,'HID+ PETITS KYSTES DES BOURSES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (170,'PHARYNGITE+LARYNGITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (171,'OEDEME DOULOUREUX+ECCHYMOSE DE LA ZONE FRONTO TEMPORALE GAUCHE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (173,'GASTRITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (174,'BRONCHITE TABAGIQUE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (175,'ABCES ANAL');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (176,'asthenie anorexie');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (177,'MYCOSE BUCCALE ET CUTANEE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (178,'TABAGISME');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (179,'NEVROSE ANGOISSE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (180,'INSOMNIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (181,'ETAT ANXIEUX');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (182,'ASTHME');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (183,'GINGIVITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (184,'VOMISSEMENTS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (185,'ECZEMA CUTANE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (186,'EX DE VIRGINITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (187,'DLRS LOMBAIRES GAUCHES INTERMITTANTES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (188,'VIRGINITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (189,'GROSSESSE DE 6MOIS ENVIRONS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (190,'SD CANAL CARPIEN');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (191,'dlrs abd et lombaires');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (192,'DLRS GENOU G');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (193,'BRULURE INDEX G');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (194,'TRAUMA CRANIEN');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (195,'RETARD STATURO PONDERAL ET PSYCHOMOTEUR');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (196,'premenopause');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (197,'DYSPNEE+POLYARTHRALGIS+PALPITATIONS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (198,'NODULE SEIN DT');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (199,'DYSMENORRHEE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (201,'NEVRALGIES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (202,'GROSSESSE 9MOIS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (203,'HYPERTRIGLYCERIDEMIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (204,'SD FEBRILE+GASTRALGIES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (205,'LITHIASE VESICULAIRE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (206,'ACNE DU DOS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (207,'ERYTISME CV');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (208,'PRECORDIALGIES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (209,'HYMEN NE PRESENTE PAS DE SIGNES DE DEFLORATION RECENTE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (210,'SUSPICION DE GOUTTE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (211,'MYCOSE DES PIEDS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (212,'ALLERGIE RESPIRATOIRE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (213,'BLESSURE POUCE DT');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (215,'TRAUMA PIED G');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (216,'LUPUS RENAL');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (217,'DLRS VERTEBRALES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (218,'SUSPICION HYPOGLYCEMIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (219,'BRONCHOPNEUMOPATHIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (220,'RETARD DES REGLES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (221,'INF URINAIRE ET GENITALE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (222,'ECZEMA DES MAINS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (223,'pas de signes de defloration recente');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (224,'DIARRHEE AIGUE NON FEBRILE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (225,'SUSP APPENDICITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (226,'ABCES SEIN DT');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (227,'ARTHROSE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (228,'TR LANGAGE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (229,'PARESTHESIES MSG MIG');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (230,'DLRS TALONS ET GENOUX');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (232,'FAUSSE COUCHE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (234,'DLRS THORACIQUES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (235,'SD FEBRILE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (236,'DLRS SCAPULOHUMERALES G+PRECORDIALGIES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (237,'TR ERECTION+HTA');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (238,'DLRS FLANC DT+VOMISSEMENTS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (239,'ANNEXITE G');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (240,'SUSPICION D APPENDICITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (241,'AEROCOLIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (242,'CYSTITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (243,'DLRS CERVICOBRACHIALES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (244,'ECV');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (246,'DLRD RHUMATISMALES DIFFUSES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (247,'FURONCLES AISSELLES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (248,'MYCOSE APP GENITAL');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (250,'FURONCLE MAIN GAUCHE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (251,'TRAUMA DES GENOUX+GASTRALGIES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (252,'GROSSESSE EVOLUTIVE DE 33SEM');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (253,'RHINOPHARYNGITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (254,'TRAUMA MAIN GAUCHE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (255,'SIGNES D ARTERIOPATHIE DIABETIQUE ');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (256,'DLRS FLANC G');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (258,'EPINES CALCANEENNES BILATERALES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (259,'PLAIE INFECTEE GENOUX DT');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (260,'ERUPTION BULLEUSE ET PRURIGINEUSE DU PIED DT');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (261,'RX GENOUX DT');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (262,'RX GENOU DT');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (263,'MENOPAUSE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (264,'PRURIT GENERALISE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (265,'INTERTRIGO GENITO FESSIER');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (266,'SINUSITE FRONTALE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (267,'PALPITATIONS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (268,'PLAIE OPERATOIRE EN COURS DE CICATRISATION');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (269,'RGO+ABCES INGUINALG');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (270,'TRAUMA OEIL DROIT');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (271,'DIARRHEE AIGUE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (272,'CHOC EMOTIF');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (273,'dlrs hd');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (274,'BRADYCARDIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (275,'POUSSEE DENTAIRE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (276,'VERRUES GENITALES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (277,'PUSTULES DU COUDE G  ET THORAX');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (278,'SUSP DE CHOLECYSTITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (279,'DLRS CERVICALES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (280,'GONOCOCCIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (281,'ACOUFENES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (282,'SUSPICION DE MALADIE DE BEHCET');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (283,'TENDINITE TALON DROIT');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (284,'DLRS SCAPULO HUMERALES G');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (285,'cernes paup inf');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (286,'ABLATION DES FILS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (287,'PHARYNGITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (288,'TRAUMA EPAULE DTE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (290,'ENTORSE GENOU G');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (291,'OEDEMES DES MAINS ET PIEDS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (292,'PARFOIS CONJONCTIVES JAUNATRES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (293,'SUSPICION DE TUBERCULOSE PULMONAIRE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (294,'RAS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (295,'GROSSESSE  EVOLUTIVE  DE 18 SEM  ENVIRONS');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (296,'GROSSESSE DE 18 SEM');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (297,'EX NORMAL APTE AU MARIAGE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (298,'point de cote costal g');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (299,'METRORRAGIES');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (300,'EPIDIDYMITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (301,'MASSE PELVIENNE DTE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (302,'ANOREXIE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (303,'TRAUMA DU BASSIN');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (304,'INF CUTANEE PIED G');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (305,'DLRS  SEIN G');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (306,'DYSPHONIE +TOUX+DYSPNEE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (307,'ORCHITE DTE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (308,'TRAUMA THORACIQUE+BRONCHITE');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (310,'DLRS HEPATIQUES ');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (311,'DLRS PIED G');
INSERT INTO `diagnostics` (`id`,`description`) VALUES (312,'URETRITE');
