INSERT INTO `examens` (`id`,`description`) VALUES (9,'aucun');
INSERT INTO `examens` (`id`,`description`) VALUES (10,'RX poignet droit');
INSERT INTO `examens` (`id`,`description`) VALUES (11,'echo urinaire');
INSERT INTO `examens` (`id`,`description`) VALUES (13,'ECHO ABD ET URINAIRES ');
INSERT INTO `examens` (`id`,`description`) VALUES (14,'ECHO ABD ET URINAIRE');
INSERT INTO `examens` (`id`,`description`) VALUES (15,'ECHOGRAPHIE OBSTETRICALE');
INSERT INTO `examens` (`id`,`description`) VALUES (16,'NFS VS ');
INSERT INTO `examens` (`id`,`description`) VALUES (17,'TEST DE GROSSESSE');
INSERT INTO `examens` (`id`,`description`) VALUES (18,'TA:18/12');
INSERT INTO `examens` (`id`,`description`) VALUES (19,'gaj urée');
INSERT INTO `examens` (`id`,`description`) VALUES (20,'bilan de grossesse');
INSERT INTO `examens` (`id`,`description`) VALUES (21,'UREE');
INSERT INTO `examens` (`id`,`description`) VALUES (22,'CREATININE');
INSERT INTO `examens` (`id`,`description`) VALUES (23,'CHOLESTEROL ');
INSERT INTO `examens` (`id`,`description`) VALUES (24,'TRIGLYCERidS');
INSERT INTO `examens` (`id`,`description`) VALUES (25,'BILAN HTA');
INSERT INTO `examens` (`id`,`description`) VALUES (26,'RX BASSIN');
INSERT INTO `examens` (`id`,`description`) VALUES (27,'RAS');
INSERT INTO `examens` (`id`,`description`) VALUES (29,'NFS - GAJ- UREE- CHOLESTEROL- TG');
INSERT INTO `examens` (`id`,`description`) VALUES (31,'BILAN DE DEBUT DE GROSSESSE');
INSERT INTO `examens` (`id`,`description`) VALUES (32,'BILAN DIABETE+ HTA');
INSERT INTO `examens` (`id`,`description`) VALUES (33,'GAJ   GPP   UREE  CREATININE  CHOLESTEROL  TRIGLYCERidS');
INSERT INTO `examens` (`id`,`description`) VALUES (34,'BILAN HEPATIQUE');
INSERT INTO `examens` (`id`,`description`) VALUES (35,'NFS VS  THYROXINE  UREE  CREATININE  GAJ  CHOLESTEROL  TRIG');
INSERT INTO `examens` (`id`,`description`) VALUES (36,'GAJ:103G/L');
INSERT INTO `examens` (`id`,`description`) VALUES (37,'COPRO PARASITO DES SELLES');
INSERT INTO `examens` (`id`,`description`) VALUES (38,'DLRS FID');
INSERT INTO `examens` (`id`,`description`) VALUES (39,'RX PIED G');
INSERT INTO `examens` (`id`,`description`) VALUES (40,'RX PIED GAUCHE');
INSERT INTO `examens` (`id`,`description`) VALUES (41,'BILAN');
INSERT INTO `examens` (`id`,`description`) VALUES (42,'HBA1C:9,oo%  UREE: 0,46 G/L  CREATININE  :13,5 mg/L');
INSERT INTO `examens` (`id`,`description`) VALUES (43,'GAJ');
INSERT INTO `examens` (`id`,`description`) VALUES (44,'EX PARASITO DES SELLES');
INSERT INTO `examens` (`id`,`description`) VALUES (45,'RX POUMON');
INSERT INTO `examens` (`id`,`description`) VALUES (46,'RX COLONNE CERVICALE F+P');
INSERT INTO `examens` (`id`,`description`) VALUES (47,'RX COLONNE LOMBO SACREE');
INSERT INTO `examens` (`id`,`description`) VALUES (48,'RX CRANE F+P');
INSERT INTO `examens` (`id`,`description`) VALUES (49,'NFS');
INSERT INTO `examens` (`id`,`description`) VALUES (50,'ECBU+ATB');
INSERT INTO `examens` (`id`,`description`) VALUES (51,'TDM CEREBRAL');
INSERT INTO `examens` (`id`,`description`) VALUES (52,'MAMMOGRAPHIE+ ECHO MAMMAIRE');
INSERT INTO `examens` (`id`,`description`) VALUES (53,'VDRL NEG TPHA NEG HB NEG  HC NEG ITN  NORMALE');
INSERT INTO `examens` (`id`,`description`) VALUES (54,'TDM DORSO LOMBAIRE');
INSERT INTO `examens` (`id`,`description`) VALUES (55,'RX COLONNE LOMBOSACREE');
INSERT INTO `examens` (`id`,`description`) VALUES (56,'RX EPAULE G');
INSERT INTO `examens` (`id`,`description`) VALUES (57,'RX THORACIQUE');
INSERT INTO `examens` (`id`,`description`) VALUES (58,'RX COLONNE DORSO LOMBAIRE');
INSERT INTO `examens` (`id`,`description`) VALUES (60,'GPP');
INSERT INTO `examens` (`id`,`description`) VALUES (61,'HBA1C  11,12%');
INSERT INTO `examens` (`id`,`description`) VALUES (62,'RX TALONS ET GENOUX');
INSERT INTO `examens` (`id`,`description`) VALUES (63,'RX TALONS');
INSERT INTO `examens` (`id`,`description`) VALUES (64,'AC URIQUE');
INSERT INTO `examens` (`id`,`description`) VALUES (65,'RX EPAULE DTE');
INSERT INTO `examens` (`id`,`description`) VALUES (66,'PSA');
INSERT INTO `examens` (`id`,`description`) VALUES (67,'RX TALON DROIT');
INSERT INTO `examens` (`id`,`description`) VALUES (68,'transaminases');
INSERT INTO `examens` (`id`,`description`) VALUES (69,'bilirubine');
INSERT INTO `examens` (`id`,`description`) VALUES (70,'HBA1C ');
INSERT INTO `examens` (`id`,`description`) VALUES (71,'RX EPAULE DTE F+P');
INSERT INTO `examens` (`id`,`description`) VALUES (72,'BILAN DE TUBERCULOSE');
INSERT INTO `examens` (`id`,`description`) VALUES (73,'DOSAGE DES ASLO');
