INSERT INTO `symptomes` (`id`,`description`) VALUES (29,'aucun');
INSERT INTO `symptomes` (`id`,`description`) VALUES (30,'Oedème douloureux du poignet droit');
INSERT INTO `symptomes` (`id`,`description`) VALUES (31,'OTALGIES DROITES+ BRULURES MICTIONNELLES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (32,'brulures mictionnelles');
INSERT INTO `symptomes` (`id`,`description`) VALUES (33,'DOULEURS ABDOMINALES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (34,'DYSURIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (35,'DOULEURS CRURALES DROITES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (36,'GROSSESSE EVOLUTIVE DE 19 SEMAINES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (37,'PALEUR');
INSERT INTO `symptomes` (`id`,`description`) VALUES (38,'symptomes');
INSERT INTO `symptomes` (`id`,`description`) VALUES (39,'ASTHENIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (40,'LOMBALGIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (41,'AEROCOLIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (43,'Douleurs et froideur des extremités');
INSERT INTO `symptomes` (`id`,`description`) VALUES (44,'arthtralgies');
INSERT INTO `symptomes` (`id`,`description`) VALUES (45,'Asthénie');
INSERT INTO `symptomes` (`id`,`description`) VALUES (46,'aménorrhée de deux mois');
INSERT INTO `symptomes` (`id`,`description`) VALUES (47,'dyspnee');
INSERT INTO `symptomes` (`id`,`description`) VALUES (49,'dyspnée');
INSERT INTO `symptomes` (`id`,`description`) VALUES (51,'obesite');
INSERT INTO `symptomes` (`id`,`description`) VALUES (52,'gonalgies');
INSERT INTO `symptomes` (`id`,`description`) VALUES (53,'Sd grippal+ Conjonctivite+Céphalées courbatures');
INSERT INTO `symptomes` (`id`,`description`) VALUES (54,'ANXIETE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (55,'sensation de gonflement axillaire droit');
INSERT INTO `symptomes` (`id`,`description`) VALUES (56,'oedème aisselle droite');
INSERT INTO `symptomes` (`id`,`description`) VALUES (57,'Cephalée');
INSERT INTO `symptomes` (`id`,`description`) VALUES (58,'vertige');
INSERT INTO `symptomes` (`id`,`description`) VALUES (59,'gonalgies chroniques');
INSERT INTO `symptomes` (`id`,`description`) VALUES (60,'FIEVRE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (61,'ANGINES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (62,'TOUX');
INSERT INTO `symptomes` (`id`,`description`) VALUES (63,'EXPECTORATION');
INSERT INTO `symptomes` (`id`,`description`) VALUES (64,'DOULEURS SCAPULO HUMERALES DTES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (65,'CONSTIPATION');
INSERT INTO `symptomes` (`id`,`description`) VALUES (66,'OTALGIES DROITES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (67,'EXPECTORATION MUCOPURULENTE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (68,'RALES SIBILANTS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (69,'GASTROENTERITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (70,'aménorrée depuis le 29/01/2012');
INSERT INTO `symptomes` (`id`,`description`) VALUES (71,'Douleurs pelviennes');
INSERT INTO `symptomes` (`id`,`description`) VALUES (73,'PYROSIS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (75,'HTA');
INSERT INTO `symptomes` (`id`,`description`) VALUES (76,'GASTRALGIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (77,'DOULEURS FID');
INSERT INTO `symptomes` (`id`,`description`) VALUES (78,'DOULEURS LOMBOSACREES POST TRAUMATIQUES DEPUIS 2 MOIS ENVIRONS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (79,'AMENORRHEE DE 8SEM ENVIRONS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (81,'douleurs thoraciques');
INSERT INTO `symptomes` (`id`,`description`) VALUES (82,'Douleurs abdominales périombilicales');
INSERT INTO `symptomes` (`id`,`description`) VALUES (83,'retention urines');
INSERT INTO `symptomes` (`id`,`description`) VALUES (84,'VARICES MI');
INSERT INTO `symptomes` (`id`,`description`) VALUES (85,'MYCOSE DES PIEDS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (86,'DEMANDE CERTIFICAT DE VIRGINITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (87,'Troubles menstruels');
INSERT INTO `symptomes` (`id`,`description`) VALUES (88,'pertes vaginales blanchatres');
INSERT INTO `symptomes` (`id`,`description`) VALUES (89,'SD GRIPPAL');
INSERT INTO `symptomes` (`id`,`description`) VALUES (90,'ENURESIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (91,'haleine fétide');
INSERT INTO `symptomes` (`id`,`description`) VALUES (92,'prurit cutané');
INSERT INTO `symptomes` (`id`,`description`) VALUES (93,'OEDEME DOULOUREUX PLANTE PIED DROIT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (94,'NERVOSITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (95,'IRRITATION');
INSERT INTO `symptomes` (`id`,`description`) VALUES (96,'SCIATALGIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (97,'dyspnée asthmatiforme');
INSERT INTO `symptomes` (`id`,`description`) VALUES (98,'rales sifflants');
INSERT INTO `symptomes` (`id`,`description`) VALUES (99,'éternuments');
INSERT INTO `symptomes` (`id`,`description`) VALUES (100,'CERVICALGIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (101,'insomnie');
INSERT INTO `symptomes` (`id`,`description`) VALUES (102,'rhinite allergique');
INSERT INTO `symptomes` (`id`,`description`) VALUES (103,'DOULEURS SCAPULAIRES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (104,'VOMISSEMENTS POSTPRANDIAUX');
INSERT INTO `symptomes` (`id`,`description`) VALUES (105,'COXALGIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (106,'INFECTION OMBILIC');
INSERT INTO `symptomes` (`id`,`description`) VALUES (108,'BOUDONNEMENT OREILLES +HTA 15/10 SUIVIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (109,'PITYRIASIS VERSICOLOR');
INSERT INTO `symptomes` (`id`,`description`) VALUES (110,'PARALYSIE DES MEMBRES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (111,'SPASTICITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (112,'GROSSESSE EVOLUTIVE DE 7SEM');
INSERT INTO `symptomes` (`id`,`description`) VALUES (113,'DIABETE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (114,'VARICE MI');
INSERT INTO `symptomes` (`id`,`description`) VALUES (116,'DOULEURS THORACIQUES DTES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (117,'Aménorrhée depuis &mois et demi');
INSERT INTO `symptomes` (`id`,`description`) VALUES (119,'pertes vaginales');
INSERT INTO `symptomes` (`id`,`description`) VALUES (120,'COLIQUES NEPHRETIQUES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (121,'OEDEME DES MI');
INSERT INTO `symptomes` (`id`,`description`) VALUES (123,'PLAIE INFECTEE DU MEDIUS GAUCHE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (124,'COLIQUES ABDOMINALES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (125,'TAKYCARDIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (126,'PRURIT ANAL ');
INSERT INTO `symptomes` (`id`,`description`) VALUES (127,'ERYTHEME VULVAIRE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (128,'GROSSESSE EVOLUTIVE DE 5MOIS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (129,'CONJONCTIVITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (130,'NAUSEES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (131,'DLRS THORACIQUES ET LOMBAIRES  ');
INSERT INTO `symptomes` (`id`,`description`) VALUES (132,'ECCHYMOSES MULTIPLES  AVP');
INSERT INTO `symptomes` (`id`,`description`) VALUES (133,'ASTHENIE  DESHYDRATATION  CACHEXIE  ANOREXIE  HEPATOMEGALIE  INCONTINENCE URINAIRE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (134,'MIGRAINE   MYALGIES RHINOPHARYNGITE  BRULURES MICTIONNELLES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (135,'TA  19/9');
INSERT INTO `symptomes` (`id`,`description`) VALUES (136,'TA  16/9');
INSERT INTO `symptomes` (`id`,`description`) VALUES (137,'crachats sanguinolents matinaux depuis 5j');
INSERT INTO `symptomes` (`id`,`description`) VALUES (138,'conjonctivite allergique');
INSERT INTO `symptomes` (`id`,`description`) VALUES (139,'SECHERESSE DE LA BOUCHE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (140,'HERPES LABIAL');
INSERT INTO `symptomes` (`id`,`description`) VALUES (141,'COLIQUES HEPATIQUES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (142,'INFECTION URINAIRE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (143,'HEMORROIDES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (144,'MYCOSE DES FESSES ');
INSERT INTO `symptomes` (`id`,`description`) VALUES (145,'LOMBOSCIATALGIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (146,'AMENORRHEE DEPUIS LE 13/06/2012');
INSERT INTO `symptomes` (`id`,`description`) VALUES (147,'PERTESGENITALES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (148,'TRAUMA OEIL GAUCHE +ROUGEUR ET DOULEURS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (149,'ECCHYMOSES MULTIPLES ET OEDEMES DES BRAS FACE  CUISSE GAUCHE ORBITE GAUCHE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (150,'ACOUFENES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (151,'DOULEURS DU BASSIN ET DES MI');
INSERT INTO `symptomes` (`id`,`description`) VALUES (153,'EPIGASTRALGIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (154,'PALPITATIONS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (155,'MYALGIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (156,'GROSSESSE EVOLUTIVE DE 7MOIS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (157,'ERUPTION CUTANEE DOS TETE ET TRONC+ FEBRICULE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (158,'PLAIE INFECTEE DU GENOUX DROIT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (159,'DORSALGIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (160,'grossesse évolutive de 32semaies');
INSERT INTO `symptomes` (`id`,`description`) VALUES (161,'POINT DE CÖTE HYPOCHONDRE G');
INSERT INTO `symptomes` (`id`,`description`) VALUES (162,'POLYARTHRALGIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (163,'CHOC EMOTIF');
INSERT INTO `symptomes` (`id`,`description`) VALUES (164,'ICTERE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (165,'DYSPAREUNIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (166,'PRURIT VULVAIRE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (167,'GROSSESSE DE 22 SEMAINES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (168,'TORTICOLIS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (169,'TRACHEOBRONCHITE FEBRILE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (170,'IMPUISSANCE SEXUELLE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (171,'DOULEURS PERIOMBILICALES DEPUIS 4J');
INSERT INTO `symptomes` (`id`,`description`) VALUES (172,'Cicatrice douloureuse  deplaie sourcil gauche');
INSERT INTO `symptomes` (`id`,`description`) VALUES (173,'hypersudation');
INSERT INTO `symptomes` (`id`,`description`) VALUES (175,'CERTIFICAT MEDICAL PRENUPTIAL');
INSERT INTO `symptomes` (`id`,`description`) VALUES (178,'DLRS PIED GAUCHE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (180,'DIARRHEE CHRONIQUE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (181,'DLRS ABDOMINALES FID');
INSERT INTO `symptomes` (`id`,`description`) VALUES (182,'TOUX+CRACHAT MUCOPURULENTS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (183,'DIARRHEE FEBRILE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (184,'BRONCHITE +FIEVRE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (185,'DLRS FID  SANS FIEVRE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (186,'OREILLONS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (187,'SURMENAGE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (188,'TROUBLES DU SOMMEIL');
INSERT INTO `symptomes` (`id`,`description`) VALUES (190,'CEPHALEES OCCIPITALES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (191,'DLRS CERVICALES ET DORSALES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (192,'DID + HTA SUIVIS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (193,'INSUFFISANCE RENALE DEBUTANTE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (194,'ANEMIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (195,'DLRS GENOU DROIT ET CHEVILLE DROITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (196,'HYPOACOUSIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (197,'ASTHENIE SEXUELLE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (198,'PRURIT INTERFESSIER');
INSERT INTO `symptomes` (`id`,`description`) VALUES (199,'CONGESTION NASALE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (200,'HEMATURIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (201,'ALLERGIE CUTANEE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (202,'DOULEURS CHEVILLE DROITE+OEDEME PIED DROIT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (203,'ALLERGIE +MYCOSE CUTANEE DU VISAGE ET AISSELLES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (204,'amenorrhée depuis 2mois environs');
INSERT INTO `symptomes` (`id`,`description`) VALUES (205,'PHARYNGITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (206,'MYCOSE DES JAMBES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (207,'douleurs des pieds');
INSERT INTO `symptomes` (`id`,`description`) VALUES (208,'AMAIGRISSEMENT RESSENTI');
INSERT INTO `symptomes` (`id`,`description`) VALUES (209,'POINT DE COTE THORACIQUE G');
INSERT INTO `symptomes` (`id`,`description`) VALUES (210,'bouffees de chaleur');
INSERT INTO `symptomes` (`id`,`description`) VALUES (211,'COLIQUES NEPHRETIQUES GAUCHES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (212,'ANOREXIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (213,'ECZEMA DES MAINS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (214,'PRURIT CUTANE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (215,'dlrs pieds');
INSERT INTO `symptomes` (`id`,`description`) VALUES (216,'ECCHYMOSES MULTIPLES AU NIVEAU DE LA TETE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (217,'RETARD DES REGLES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (219,'PRUTIT GENITAL');
INSERT INTO `symptomes` (`id`,`description`) VALUES (220,'CRISE D ASTHME');
INSERT INTO `symptomes` (`id`,`description`) VALUES (221,'COLOPATHIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (222,'ERUPTION CUTANEE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (223,'FRISSONS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (224,'DLRS DENTAIRES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (225,'COURBATURES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (226,'HERNIE INGUINALE DTE+PETITS KYSTES DES BOURSES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (227,'DYSPHONIE+ DYSPHAGIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (228,'AGRESSION   OEDEME DOULOUREUX +ECCHYMOSE DE LA ZONE FRONTO TEMPORALE GAUCHE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (230,'PRECORDIALGIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (231,'BRONCHITE TABAGIQUE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (232,'AMAIRISSEMENT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (233,'DESHYDRATATION');
INSERT INTO `symptomes` (`id`,`description`) VALUES (234,'ABCES ANAL');
INSERT INTO `symptomes` (`id`,`description`) VALUES (235,'OXYURES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (236,'PETECHIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (238,'GINGIVITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (239,'APHTES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (242,'TR COMPORTEMENT ');
INSERT INTO `symptomes` (`id`,`description`) VALUES (243,'DLRS MUSCULAIRES DU FLANC GAUCHE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (244,'ALLERGIE RESPIRATOIRE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (245,'DLRS FLANC DT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (246,'LOMBALGIES GAUCHES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (247,'REGLES IRREGULIERES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (249,'DLRS LOMBAIRES GAUCHES INTERMITTANTES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (251,'SAIGNEMENT GENITAL');
INSERT INTO `symptomes` (`id`,`description`) VALUES (252,'dlrs thoraciques g');
INSERT INTO `symptomes` (`id`,`description`) VALUES (253,'dlrs abd et lombaires');
INSERT INTO `symptomes` (`id`,`description`) VALUES (254,'brulure index gauche');
INSERT INTO `symptomes` (`id`,`description`) VALUES (255,'dlrs genou gauche');
INSERT INTO `symptomes` (`id`,`description`) VALUES (256,'TRAUMA CRANIEN');
INSERT INTO `symptomes` (`id`,`description`) VALUES (257,'ECCHYMOSE PERIORBITALEDTE+OEDEME ET DLRS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (258,'DLRS GENOU DROIT+OEDEME');
INSERT INTO `symptomes` (`id`,`description`) VALUES (259,'RETARD STATURO PONDERAL ET PSYCHOMOTEUR');
INSERT INTO `symptomes` (`id`,`description`) VALUES (260,'DLRS COSTALES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (261,'ERYTHEME INTERFESSIER');
INSERT INTO `symptomes` (`id`,`description`) VALUES (262,'VARICELLE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (263,'SUSPICION DE NODULE DU SEIN DT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (264,'DYSMENORRHEE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (265,'DLRS PELVIENNES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (266,'APTITUDE PHYSIQUE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (267,'LUX HANCHE GAUCHE TRAITEE PAR PROTHESE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (268,'DISCARTHROSE L1L2');
INSERT INTO `symptomes` (`id`,`description`) VALUES (269,'NEVRALGIES DES MEMBRES ET THORAX');
INSERT INTO `symptomes` (`id`,`description`) VALUES (270,'DLRS TESTICULAIRES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (271,'dlrs talon dt');
INSERT INTO `symptomes` (`id`,`description`) VALUES (272,'GROSSESSE 9MOIS NORMALE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (273,'TRIGLYCERIDES ELEVEES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (274,'FURONCLES DU DOS ET EPAULES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (275,'ERYTISME CV');
INSERT INTO `symptomes` (`id`,`description`) VALUES (276,'EX VIRGINITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (277,'DLRS DES ORTEILS+ MYCOSE DES PIEDS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (278,'PARESTHESIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (279,'DLRS STERNALES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (281,'PRURIT GENERALISE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (283,'BLESSURE POUCE DT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (285,'ERUPTION CUT ALLERGIQUE DES MAINS ET PIEDS ');
INSERT INTO `symptomes` (`id`,`description`) VALUES (286,'DLRS FIG');
INSERT INTO `symptomes` (`id`,`description`) VALUES (287,'ERUPTION DU VISAGE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (288,'DLRS VERTEBRALES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (289,'DLRS PELVIENNES SOUS OMBILICALES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (290,'DLRS ABD');
INSERT INTO `symptomes` (`id`,`description`) VALUES (292,'DYSURIE+POLLAKIURIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (294,'DIARRHEE AIGUE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (295,'ABCES SEIN DT A REPETITION');
INSERT INTO `symptomes` (`id`,`description`) VALUES (296,'ARTHROSE VERTEBRALE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (298,'TR LANGAGE APRES CHOC EMOTIONNEL');
INSERT INTO `symptomes` (`id`,`description`) VALUES (299,'HBA1C  11,12%');
INSERT INTO `symptomes` (`id`,`description`) VALUES (300,'PARESTHESIES MSG MIG');
INSERT INTO `symptomes` (`id`,`description`) VALUES (301,'DLRS TALONS ET GENOUX');
INSERT INTO `symptomes` (`id`,`description`) VALUES (302,'METRORRAGIES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (303,'DLRS SCAPULOHUMERALES GAUCHES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (304,'ERECTION INSUFFISANTE+HTA');
INSERT INTO `symptomes` (`id`,`description`) VALUES (305,'DLRS CERVICOBRACHIALES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (306,'PARESTHESIES DES CUISSES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (307,'URINES FONCEES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (309,'FURONCLES AISSELLES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (310,'PRURIT APP GENITAL');
INSERT INTO `symptomes` (`id`,`description`) VALUES (311,'PIQURE INSECTE INFECTEE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (312,'TRAUMA DES GENOUX');
INSERT INTO `symptomes` (`id`,`description`) VALUES (313,'GROSSESSE EVOLUTIVE DE 8MOIS ENVIRONS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (316,'DLRS MAIN GAUCHE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (317,'DLRS CUISSE DTE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (318,'DLRS JAMBE GAUCHE ET GROS ORTEIL DT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (320,'DLRS FLANC G');
INSERT INTO `symptomes` (`id`,`description`) VALUES (321,'PLAIE INFECTEE GENOUX DT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (322,'BULLES DU CREUX DU PIED DT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (323,'PRURIT DU PIED DT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (324,'DLRS SCAPULO HUMERALES DTES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (325,'MYALGIES DE CUISSES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (326,'ERYTHEME GENITAL ET INTERFESSIER');
INSERT INTO `symptomes` (`id`,`description`) VALUES (327,'PLAIE OPERATOIRE EN COURS DE CICATRISATION');
INSERT INTO `symptomes` (`id`,`description`) VALUES (328,'ERUCTATIONS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (329,'REFLUX GO');
INSERT INTO `symptomes` (`id`,`description`) VALUES (330,'ABCES INGUINAL G');
INSERT INTO `symptomes` (`id`,`description`) VALUES (331,'TRAUMA OEIL DROIT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (332,'DLRS CERVICALES ET CRURALES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (333,'FURONCLE DU GENOUX G');
INSERT INTO `symptomes` (`id`,`description`) VALUES (334,'ERUPTION CUTANEE PRURIGINEUSE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (335,'ONYCHOMYCOSE DES PIEDS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (336,'POUSSEE DENTAIRE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (337,'AEROPHAGIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (338,'VERRUES GENITALES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (339,'PUSTULES DU COUDE G  ET THORAX');
INSERT INTO `symptomes` (`id`,`description`) VALUES (340,'ECOULEMENT URETRAL');
INSERT INTO `symptomes` (`id`,`description`) VALUES (341,'DLRS MI');
INSERT INTO `symptomes` (`id`,`description`) VALUES (342,'ASCITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (343,'DLRS TALON DROIT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (344,'Cernes au niveau des paupieres inf');
INSERT INTO `symptomes` (`id`,`description`) VALUES (345,'RHINOPHARYNGITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (346,'SOINS POST CHOLYCYSTECTOMIE PAR COELIOSCOPIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (347,'GLOSSITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (348,'TRAUMA EPAULE DTE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (349,'MIGRAINE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (350,'VIRGINITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (351,'TR ERECTILES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (352,'POINT DE COTE THORACIQUE DT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (353,'ENTORSE GENOU G');
INSERT INTO `symptomes` (`id`,`description`) VALUES (355,'DLRS +OEDEMES DES MAINS ET PIEDS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (356,'PARFOIS CONJONCTVES JAUNATRES ');
INSERT INTO `symptomes` (`id`,`description`) VALUES (357,'DLRS DES 2 GENOUX');
INSERT INTO `symptomes` (`id`,`description`) VALUES (358,'HEMOPTYSIE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (359,'PATIENT QUI SUIT UN REGIME HYPOCALORIQUE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (360,'EX NORMAL');
INSERT INTO `symptomes` (`id`,`description`) VALUES (362,'DLRS POIGNET DT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (364,'MASSE PELVIENNE  DTE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (366,'TRAUMA DU BASSIN');
INSERT INTO `symptomes` (`id`,`description`) VALUES (367,'DLRS +OEDEME DU PIED G');
INSERT INTO `symptomes` (`id`,`description`) VALUES (368,'DLRS ISOLEES DU SEIN G');
INSERT INTO `symptomes` (`id`,`description`) VALUES (369,'DLRS DES TALONS');
INSERT INTO `symptomes` (`id`,`description`) VALUES (370,'DYSPHONIE +TOUX+ DYSPNEE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (371,'DLRS TESTICULAIRES DTES');
INSERT INTO `symptomes` (`id`,`description`) VALUES (372,'DLRS POST TRAUMA THORACIQUE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (373,'DLRS COTYLE DT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (374,'DLRS GROS ORTEUIL DT');
INSERT INTO `symptomes` (`id`,`description`) VALUES (375,'DLRS HD');
INSERT INTO `symptomes` (`id`,`description`) VALUES (376,'DLRS PIED G');
INSERT INTO `symptomes` (`id`,`description`) VALUES (377,'URETRITE');
INSERT INTO `symptomes` (`id`,`description`) VALUES (378,'BRONCHITE CHRONIQUE');
